### ISSUE TITLE
Define color scheme

### ISSUE THREAD

**Issue by MrSunshyne** [mscraftsman/devcon2020#10]

**Comment by isitlunchtimeyet** [comment]
Since we are going with the comic's theme, I reckon a soft pastel of comic book style colors will be suitable.

dark red - #902724
red - #f23c27 
yellow - #f7d281 
blue -  #1b729f 
dark blue- #1a323e

![a7ce7bb4abdc8bb1defcbaaab20c41cf (1)](https://user-images.githubusercontent.com/36814895/73156895-b28eee00-40f8-11ea-98ba-e9f5044ca858.png)

**Comment by MrSunshyne** [comment]
These look pretty good. Thanks for the recommendation

**Comment by Saamiyah** [comment]
Based on the brochure that is available, the colors are very vibrant, hence I think it would be convenient to keep the same colors on the website as well. For instance, the color palette I would suggest would be this one.

![3c8e9018419415 562c93f593513](https://user-images.githubusercontent.com/7201256/73255542-c2caca00-41d9-11ea-868c-44e89f21e3c8.png)

**Comment by Saamiyah** [comment]
However, we could also pick one color palette for specific pages that corresponds to different famous comic characters.

**Comment by MrSunshyne** [comment]
These look good. We need to define(pick a hex for each) these colors :

- gray
- red
- orange
- yellow
- green
- teal
- blue
- indigo
- purple
- pink

Which will then be integrated in [tailwind.config.js](https://github.com/mscraftsman/devcon2020/blob/master/tailwind.config.js)

**Comment by Saamiyah** [comment]
Hello, I'm on it.

**Comment by MrSunshyne** [comment]
resolved in PR https://github.com/mscraftsman/devcon2020/pull/27
